<html lang="en" xmlns:ext="http://www.extjs.com/docs">
<head>
    <base href="http://agan/template/manager/" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>ExtJS 3.2.1 API Documentation</title>
    <link rel="stylesheet" type="text/css" href="resources/css/ext-all.css" />
    <link rel="stylesheet" type="text/css" href="docs/resources/docs.css" />
    <link rel="stylesheet" type="text/css" href="docs/resources/style.css" />
    <link rel="shortcut icon" href="docs/resources/favicon.ico" />
    <link rel="icon" href="docs/resources/favicon.ico" />
 	<script type="text/javascript" src="ext-base-debug-w-comments.js"></script>
    <script type="text/javascript" src="ext-all-debug-w-comments.js"></script>
    <script type="text/javascript" src="ux/TabCloseMenu.js"></script>
    <script type="text/javascript" src="docs/resources/docs.js"></script>
    <script type="text/javascript" src="tree.js"></script>
    <style>
    .x-tip .x-tip-body{font-size:13px;}
    </style>
</head>
<body scroll="no" id="docs">
  <div id="loading-mask" style=""></div>
  <div id="loading">
    <div class="loading-indicator"><img src="docs/resources/extanim32.gif" width="32" height="32" style="margin-right:8px;" align="absmiddle"/>Loading...</div>
  </div>

  <div id="header">
	<a href="http://extjs.com" style="float:right;margin-right:10px;"><img src="docs/resources/extjs.gif" style="width:83px;height:24px;margin-top:1px;"/></a>

	<div class="api-title">ExtJS 3.2.1 API Documentation</div>
  </div>

  <div id="classes"></div>

  <div id="main"></div>
  <select id="search-options" style="display:none">
    <option>Starts with</option>
    <option>Ends with</option>
    <option>Any Match</option>
</select>
  </body>
</html>
